### ISSUE TITLE
HL2 Starts Up Distorted

### ISSUE THREAD

**Issue by luarvique** [jancona/hpsdrconnector#14]
Sorry for filing another issue, but I am essentially stress-testing the HL2 setup in OWRX, and some things keep coming up.

It looks like when HL2 is first initialized (i.e. had no receivers running on it prior), it comes up with distortions. Once I change the center_frequency at least once, distortions disappear. They are also not present in secondary receivers. Only the initial one will have them.

Here is what it looks like:

![image](https://github.com/jancona/hpsdrconnector/assets/3293202/06260f0e-d82e-44cb-849d-941a394c4034)

While this is unlikely due to hpsdrconnector, will it be possible to work around this issue? Maybe change the frequency twice on startup, with a small delay, to make HL2 come to its senses?

**Comment by jancona** [comment]
I've seen this occasionally, including last night, but I can't reproduce it. When it happened last night, nothing I tried within OWRX fixed it. Even restarting OWRX didn't help. I had to power-cycle the HL2. Do you have a way to cause it to happen? Could you point me to the code for your workaround?

**Comment by luarvique** [comment]
It is pretty repeatable for me, with ~70-80% probability. To make it happen:

1) Make sure you are using either original OWRX or pre-1.2.45 OWRX+, since OWRX+ 1.2.45 has a workaroun for it.

2) Make sure nothing is using HL2, hpsdrconnector server is not running, i.e. HL2 is "cold".

3) Select an HL2 profile in OWRX and see it glitch. In my experience, 40m band is the most affected for some reason, but it does happen in other bands as well.

The current workaround is pretty dumb and comes down to force-setting center frequency after SDR source has started:

https://github.com/luarvique/openwebrx/blob/c3d651da748361daa3bb1c66e0e86eb04737ab59/owrx/source/hpsdr.py#L32

At the very least, the same workaround can (and should) be added to hpsdrconnector. It may indicate that the first hpsdrconnector client somehow fails to set its rxFrequency right, or something of this kind.

**Comment by luarvique** [comment]
PS: If you are running OWRX+ with side-stepping enabled, fixing the issue is as simple as **right-clicking** one of the big round arrow buttons at the top: this changes center frequency up or down, causing center frequency update at HL2.

**Comment by jancona** [comment]
I still can't reproduce this. Theoretically, force-setting the center frequency shouldn't make any difference, since the exact same call is made when adding the receiver. So I'm wondering if there's either a race in my code or a timing issue with the hardware. I made some changes that might help. When you have a chance, can you see if they made any difference? Thanks!

**Comment by luarvique** [comment]
Updated from GIT, built, installed, disabled OWRX workaround, will need ~24 hours to see if anything interesting happens.

**Comment by luarvique** [comment]
The change you made apparently fixed the issue. Have not seen it happen in a day of use (usually does not take much to recreate).

**Comment by jancona** [comment]
Sounds good
