### ISSUE TITLE
gain value in decimal format

### ISSUE THREAD

**Issue by takgr** [jancona/hpsdrconnector#3]
openwebrx passes gain in decimal format and hpsdrconnector does not accept that

owrx.source - INFO - Started sdr source: hpsdrconnector --samplerate 96000 --gain 30.0 --radio 192.168.1.131 --frequency 28074000 -p 44551 -c 56021

invalid value "30.0" for flag -gain: parse error

**Comment by jketterl** [comment]
See: https://github.com/jketterl/openwebrx/issues/256

**Comment by jancona** [comment]
As the issue that @jketterl linked to shows, this has been fixed in the OpenWebRX develop branch (see https://github.com/jketterl/openwebrx/pull/235 for more details). Until there's an official release, you will have to build OpenWebRX from source or use one of the experimental builds.
