### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by dg9bja** [jancona/hpsdrconnector#5]
Hi,
I am looking for a way to get my red pitaya HPSDR channel's into SoapySDR because my used application is only able to use SoapySDR.
Is it possible to use this connector between the red pitaya and SoapySDR? I did not find any hpsdr driver for SoapySDR until now.

**Comment by jancona** [comment]
I don't think hpsdrconnector would be useful for that. I see you found https://github.com/pothosware/SoapySDR/issues/260, but it appears no one has written a driver. This connector allows OpenWebRX to use HPSDR radios without using SoapySDR. Sorry and good luck in your search.
