### ISSUE TITLE
hpsdrconnector and radioberry on one device is not working

### ISSUE THREAD

**Issue by pa3gsb** [jancona/hpsdrconnector#8]
Hi Jim,

There are some experiments going on to connect the radioberry; also an hpsdr protocol radio device to the hpsdrconnecor on one computer; a RPI-4 device.

When running owrx a message occurs port 1024 is already in use.

The firmware of the radioberry implements the ethernet part of an HPSDR radio ; like the discovery.
Therefor the port 1024 is required; but as mentioned the hpsdrconnector is also using the 1024 port; are you willing to change the ethernet port to a random port id which you can use for searching the HPSDR devices so the both application are not having port conflict?

For instance the pihpsdr program which is also doing a discovery uses also an other port for searching openhpsdr radio devices.

If fixed it is possible to have 6 RX profiles on one device in OWRX when running a radioberry and the connector.

Hope you are willing to have a solution for us. 

Looking forward to your reaction.

73 Johan
PA3GSB

**Comment by jancona** [comment]
This should be fixed in release [0.6.3](https://github.com/jancona/hpsdrconnector/releases/tag/v0.6.3). I'm not sure when that will show up in OWRX. It may take awhile before it shows in the OWRX development releases.

**Comment by jancona** [comment]
I'm now seeing it in the development Docker release: https://hub.docker.com/r/jketterl/openwebrx/tags

**Comment by pa3gsb** [comment]
Hi Jim

Tnx. I tried it with docker and it is working. 

73 Johan
PA3GSB
