### ISSUE TITLE
Packaging hpsdrconnector for OWRX+

### ISSUE THREAD

**Issue by luarvique** [jancona/hpsdrconnector#9]
Hello, Jim!

I am the developer behind OpenWebRX+, a somewhat improved fork of the original OpenWebRX. Recently, multiple people asked me to provide support for your latest hpsdrconnector version. I have imported your changes to the OWRX (owrx/source/hpsdr.py), but am looking for a way to build an hpsdrconnector DEB package. 

Since your repository does not contain any DEB build files, could you explain how you are packaging it?

**Comment by jancona** [comment]
The packages in this repo are built by Github actions using https://github.com/jiro4989/build-deb-action. You can see the configuration in https://github.com/jancona/hpsdrconnector/blob/master/.github/workflows/go.yml

The OpenWebRX packages are built using the config in https://github.com/openwebrx/hpsdr-debian/tree/debian/sid and https://github.com/openwebrx/hpsdrconnector-debian/tree/debian/sid 

The connector depends on a separate Go library and Jakob chose to package them separately, even though the hpsdrconnector binary is static and doesn't depend on a shared library at runtime, only during compilation. The deb packaging in this repo doesn't do that, it just build a single package. I don't know enough about Debian packaging to have an informed opinion on which approach is correct.

Thanks for taking this on. Let me know if I can help with anything.

**Comment by luarvique** [comment]
I see. Jakob is likely packaging that library in case someone may want it for other projects. I guess the simplest thing for me is just to build the https://github.com/openwebrx/hpsdrconnector-debian/tree/debian/sid relative to my current OWRX+ libraries and put the package into OWRX+ repository. Am I on the right path? In fact, is it necessary at all, or does the main OWRX repository (not devel!) already contain the latest hpsdrconnector?

**Comment by jancona** [comment]
There is a version in the main OWRX repository, but there have been a number of changes in the last few weeks that are only in the Experimental repository. I think those are what your users are looking for. 

If you don't have it already, you might also want this PR that affects the HPSDR functionality: https://github.com/jketterl/openwebrx/pull/358.

**Comment by luarvique** [comment]
Yeah, these changes have been introduced into OWRX+, just need to make sure I have the matching hpsdrconnector package where OWRX+ users can get it.

**Comment by luarvique** [comment]
All right. After hopelessly trying to figure out how git-buildpackage works, I have come to conclusion that the simplest solution is to take the binary packages you built and place them into repository with the OWRX+ packages. They do appear to install and run for me, so it is worth a try.
